from __future__ import annotations

from typing import Any, Protocol

from . import schema
from ._methods import CreateElicitationRequest, CreateElicitationResponse, SetConfigOptionRequest

__all__ = ["Agent", "Client"]


class Agent(Protocol):
    async def initialize(self, request: schema.InitializeRequest) -> schema.InitializeResponse: ...

    async def login(self, request: schema.LoginAuthRequest) -> schema.LoginAuthResponse | None: ...

    async def logout(self, request: schema.LogoutAuthRequest) -> schema.LogoutAuthResponse | None: ...

    async def list_providers(self, request: schema.ListProvidersRequest) -> schema.ListProvidersResponse: ...

    async def set_provider(self, request: schema.SetProviderRequest) -> schema.SetProviderResponse | None: ...

    async def disable_provider(
        self, request: schema.DisableProviderRequest
    ) -> schema.DisableProviderResponse | None: ...

    async def new_session(self, request: schema.NewSessionRequest) -> schema.NewSessionResponse: ...

    async def list_sessions(self, request: schema.ListSessionsRequest) -> schema.ListSessionsResponse: ...

    async def delete_session(self, request: schema.DeleteSessionRequest) -> schema.DeleteSessionResponse | None: ...

    async def fork_session(self, request: schema.ForkSessionRequest) -> schema.ForkSessionResponse: ...

    async def resume_session(self, request: schema.ResumeSessionRequest) -> schema.ResumeSessionResponse: ...

    async def close_session(self, request: schema.CloseSessionRequest) -> schema.CloseSessionResponse | None: ...

    async def set_config_option(self, request: SetConfigOptionRequest) -> schema.SetSessionConfigOptionResponse: ...

    async def prompt(self, request: schema.PromptRequest) -> schema.PromptResponse | None: ...

    async def cancel(self, notification: schema.CancelSessionNotification) -> None: ...

    async def message_mcp(self, message: schema.MessageMcpRequest | schema.MessageMcpNotification) -> Any: ...

    async def start_nes(self, request: schema.StartNesRequest) -> schema.StartNesResponse: ...

    async def suggest_nes(self, request: schema.SuggestNesRequest) -> schema.SuggestNesResponse: ...

    async def accept_nes(self, notification: schema.AcceptNesNotification) -> None: ...

    async def reject_nes(self, notification: schema.RejectNesNotification) -> None: ...

    async def close_nes(self, request: schema.CloseNesRequest) -> schema.CloseNesResponse | None: ...

    async def did_open(self, notification: schema.DidOpenDocumentNotification) -> None: ...

    async def did_change(self, notification: schema.DidChangeDocumentNotification) -> None: ...

    async def did_close(self, notification: schema.DidCloseDocumentNotification) -> None: ...

    async def did_save(self, notification: schema.DidSaveDocumentNotification) -> None: ...

    async def did_focus(self, notification: schema.DidFocusDocumentNotification) -> None: ...

    async def ext_method(self, method: str, params: Any) -> Any: ...

    async def ext_notification(self, method: str, params: Any) -> None: ...

    def on_connect(self, connection: Client) -> None: ...


class Client(Protocol):
    async def request_permission(
        self,
        request: schema.RequestPermissionRequest,
    ) -> schema.RequestPermissionResponse: ...

    async def session_update(self, notification: schema.UpdateSessionNotification) -> None: ...

    async def connect_mcp(self, request: schema.ConnectMcpRequest) -> schema.ConnectMcpResponse: ...

    async def message_mcp(self, message: schema.MessageMcpRequest | schema.MessageMcpNotification) -> Any: ...

    async def disconnect_mcp(
        self,
        request: schema.DisconnectMcpRequest,
    ) -> schema.DisconnectMcpResponse | None: ...

    async def create_elicitation(self, request: CreateElicitationRequest) -> CreateElicitationResponse: ...

    async def complete_elicitation(self, notification: schema.CompleteElicitationNotification) -> None: ...

    async def ext_method(self, method: str, params: Any) -> Any: ...

    async def ext_notification(self, method: str, params: Any) -> None: ...

    def on_connect(self, connection: Agent) -> None: ...
